const pbquestion = [
  'Carimbo de data/hora',
  'Nome de usuário',
  'De 0 a 10, o quão satisfeito você está em relação a administração do servidor?',
  'De 0 a 10, o quão satisfeito você está em relação aos eventos do servidor?',
  'De 0 a 10, como você classifica a estabilidade e desempenho do servidor?',
  'De 0 a 10, o quão balanceadas você considera as mecânicas e sistemas do servidor?',
  'De 0 a 10, qual seu nível de diversão jogando na Pokedrock Brasil?',
  'De 0 a 10, que nota você daria para essa temporada em relação a temporada passada?',
  'De 0 a 10, qual a chance de você recomendar o servidor para um amigo?',
  'Como você avalia a comunidade do servidor?',
  'Como você avalia o suporte recebido? (Tickets, dúvidas etc.)',
  'Como está a frequência de atualizações?',
  'O que você mais gosta no servidor?',
  'O que você acha dos Vips e Kit Vips?',
  'O que você espera sobre a nova moeda, Ether?',
  'O que você acha que poderia melhorar?',
  'Tem alguma sugestão de conteúdo, evento ou sistema que gostaria de ver no futuro?',
  'Deseja deixar alguma crítica, elogio ou comentário geral?',
];

const pbdata = [
  [
    '2025/07/23 12:11:08 PM GMT-3',
    'yaagoo143@gmail.com',
    '10',
    '6',
    '5',
    '7',
    '9',
    '',
    '9',
    'Boa',
    'Muito boa',
    'Neutra',
    '',
    'Bons ',
    'Mais facilidade de se obter',
    '',
    '',
    '',
  ],
  [
    '2025/07/23 12:40:22 PM GMT-3',
    'guizarro13@gmail.com',
    '10',
    '10',
    '10',
    '10',
    '10',
    '10',
    '10',
    'Muito boa',
    'Muito boa',
    'Muito boa',
    'Os eventos ',
    'Bom queria que tivesse um sorteio dos vips ',
    'Eu não sei muito sobre mas deve ser legal',
    '',
    '',
    '',
  ],
  [
    '2025/07/23 12:40:43 PM GMT-3',
    'luisnesh33@gmail.com',
    '8',
    '5',
    '10',
    '5',
    '10',
    '5',
    '10',
    'Boa',
    'Boa',
    'Neutra',
    'Das pessoas que jogam, isso traz um pouco de diversão em conjunto',
    'N sei nem oq é isso',
    'N sei oq é isso tbm',
    'N tenho experiencia para opinar sobre isso',
    'Torneios e combates',
    'Eu acabo de entrar no servidor e sou bem recebido, espero que a comunidade cresça e n deixe de existir',
  ],
  [
    '2025/07/23 12:47:03 PM GMT-3',
    'joaoantoniocarvalho328@gmail.com',
    '10',
    '10',
    '10',
    '10',
    '10',
    '10',
    '10',
    'Muito boa',
    'Muito boa',
    'Muito boa',
    'As formas dos pokémons e as megas',
    'Não posso responder direito pois eu não tenho',
    'Que seja melhor do que a moeda normal',
    'Criarem um mundo so pra construir casas e um mundo pra pegar matérias que fica reiniciando',
    'Um evento de batalha que so pode usar um time em comum',
    'O servidor é ótimo, mais podiam adicionar algumas coisas tipo batalhas ranqueadas, menos de ajuda coisas assins',
  ],
  [
    '2025/07/23 12:49:01 PM GMT-3',
    'ruanpablo0802@gmail.com',
    '10',
    '8',
    '8',
    '9',
    '7',
    '7',
    '10',
    'Muito boa',
    'Muito boa',
    'Boa',
    '',
    'Muito útil além de manter o server',
    'Me parece bem promissor',
    'To achando o jogo meio parado, deveriam ter mais conteúdos pra evitar a repetição ',
    '',
    '',
  ],
  [
    '2025/07/23 12:51:34 PM GMT-3',
    'brayanrafael2009gg@gmail.com',
    '1',
    '8',
    '8',
    '3',
    '4',
    '10',
    '1',
    'Neutra',
    'Boa',
    'Neutra',
    'Os eventos de batalhas',
    'Não tem muito o que achar sem eles n teria servidor ',
    'Que seja dboa de conseguir ',
    'A administração do servidor ',
    '',
    'Sinceramente, a administração do servidor é horrível eu nunca vi um servidor onde um ADM participa de uma equipe, rouba pra equipe que ele faz parte, ensina a roubar e passa pano se algm da equipe dele for pego, agora se for outro player já toma ban e sinceramente muitos ADM n sabem nem discutir sempre querem ter a razão, e sempre os outros estão errados, eles n se importam de ver os dois lados de uma briga se uma pessoa se ofendeu pelo oq a outra disse eles n se dão nem ao luxo de ir ver c a outra pessoa pediu perdão ou se ela está arrependida, eles simplesmente só vão dando ban e n se importam se a outra pessoa chegou a pedir dscp ou etc, sinceramente a administração desse servidor é triste é um monte de criança com cargo alto q fica fazendo merda se continuar assim n vai levar nem um ano pro servidor afundar',
  ],
  [
    '2025/07/23 12:55:32 PM GMT-3',
    'pdroz007xbox@gmail.com',
    '7',
    '7',
    '8',
    '8',
    '10',
    '8',
    '10',
    'Boa',
    'Neutra',
    'Neutra',
    'Base da equipe Rocket coisa linda',
    'Num sei',
    'Ideia bem legal',
    'Ginásios e cidades do mundo aventura',
    'Prêmio pra base mais bonita e criativa',
    '',
  ],
  [
    '2025/07/23 1:04:45 PM GMT-3',
    'bentescaiomonteiro@gmail.com',
    '9',
    '10',
    '6',
    '8',
    '10',
    '10',
    '10',
    'Boa',
    'Muito boa',
    'Neutra',
    'Todas as amizades que eu fiz <3',
    'Zica',
    'Não gostei muito não:p',
    'O desempenho,pessoas ficam fazendo farms e deixa o server todo ligado:/',
    'Eventos para divertir a comunidade por exemplo: Procure tal pokémon,se escondam em tal área. Ia ser legal',
    'Amo e admiro muito vcs adms <3',
  ],
  [
    '2025/07/23 1:14:14 PM GMT-3',
    'anthonybleck2227@gmail.com',
    '7',
    '9',
    '10',
    '6',
    '7',
    '5',
    '7',
    'Neutra',
    'Neutra',
    'Neutra',
    '',
    '',
    '',
    '',
    '',
    '',
  ],
  [
    '2025/07/23 1:17:57 PM GMT-3',
    'hckyu0856@gmail.com',
    '10',
    '10',
    '10',
    '10',
    '10',
    '10',
    '10',
    'Muito boa',
    'Muito boa',
    'Muito boa',
    'Eventos (nem é porque sou eu que estar fazendo 🤡)',
    'Muito bom ',
    'Lucrativa ',
    'Talvez os líderes voltar ou não, sei lá ',
    'Mais divulgação ',
    'O hell é lindo ',
  ],
  [
    '2025/07/23 1:22:40 PM GMT-3',
    'rafaeuplayer@gmail.com',
    '10',
    '10',
    '10',
    '10',
    '10',
    '10',
    '10',
    'Muito boa',
    'Muito boa',
    'Muito boa',
    '',
    '',
    '',
    '',
    '',
    '',
  ],
  [
    '2025/07/23 3:20:19 PM GMT-3',
    'andre300minicraft@gmail.com',
    '2',
    '5',
    '3',
    '4',
    '6',
    '7',
    '8',
    'Neutra',
    'Ruim',
    'Ruim',
    '',
    '',
    '',
    '',
    '',
    '',
  ],
  [
    '2025/07/23 3:31:27 PM GMT-3',
    'ruxdan9200@gmail.com',
    '3',
    '8',
    '7',
    '8',
    '4',
    '6',
    '2',
    'Neutra',
    'Neutra',
    'Boa',
    'O juan',
    'Ok',
    'Boa, mas os adm vão roubar pra seus amiguinhos',
    'Tirar o Pedro como administrador, ele rouba para seus amiguinhos, mesma coisa do hell mas ele é o dono agora, então infelizmente não da',
    '',
    'Sinceramente, a administração do servidor é horrível eu nunca vi um servidor onde um ADM participa de uma equipe, rouba pra equipe que ele faz parte, ensina a roubar e passa pano se algm da equipe dele for pego, agora se for outro player já toma ban e sinceramente muitos ADM n sabem nem discutir sempre querem ter a razão, e sempre os outros estão errados, eles n se importam de ver os dois lados de uma briga se uma pessoa se ofendeu pelo oq a outra disse eles n se dão nem ao luxo de ir ver c a outra pessoa pediu perdão ou se ela está arrependida, eles simplesmente só vão dando ban e n se importam se a outra pessoa chegou a pedir dscp ou etc, sinceramente a administração desse servidor é triste é um monte de criança com cargo alto q fica fazendo merda se continuar assim n vai levar nem um ano pro servidor sumir Pedro e Hell são péssimos adms',
  ],
];

const result = document.getElementById('result');

let id = 1
for (const data of pbdata) {
  const h2 = document.createElement("h2")
  h2.setAttribute("class", "title")
  h2.textContent = `Resposta ${id}`
  id++
  
  const p = document.createElement("p")
  p.innerHTML = p.innerHTML = `
  email: ${data[1]}<br><br>
  <strong>${pbquestion[2]}</strong><br>R: ${data[2]}<br><br>
  <strong>${pbquestion[3]}</strong><br>R: ${data[3]}<br><br>
  <strong>${pbquestion[4]}</strong><br>R: ${data[4]}<br><br>
  <strong>${pbquestion[5]}</strong><br>R: ${data[5]}<br><br>
  <strong>${pbquestion[6]}</strong><br>R: ${data[6]}<br><br>
  <strong>${pbquestion[7]}</strong><br>R: ${data[7]}<br><br>
  <strong>${pbquestion[8]}</strong><br>R: ${data[8]}<br><br>
  <strong>${pbquestion[9]}</strong><br>R: ${data[9]}<br><br>
  <strong>${pbquestion[10]}</strong><br>R: ${data[10]}<br><br>
  <strong>${pbquestion[11]}</strong><br>R: ${data[11]}<br><br>
  <strong>${pbquestion[12]}</strong><br>R: ${data[12]}<br><br>
  <strong>${pbquestion[13]}</strong><br>R: ${data[13]}<br><br>
  <strong>${pbquestion[14]}</strong><br>R: ${data[14]}<br><br>
  <strong>${pbquestion[15]}</strong><br>R: ${data[15]}<br><br>
  <strong>${pbquestion[16]}</strong><br>R: ${data[16]}<br><br>
  <strong>${pbquestion[17]}</strong><br>R: ${data[17]}
`
  
  result.appendChild(h2)
  result.appendChild(p)
}